# API config
base.url=https://reqres.in
reqres.api.key=reqres_76e77e2195334d34bbb537e52fdfa2ae
user.agent=reqres-qa-tests/1.0
jsonplaceholder.base.url=https://jsonplaceholder.typicode.com

# UI config
ui.baseUrl=https://www.saucedemo.com
ui.username=standard_user
ui.password=secret_sauce
browser=chrome

# PostgreSQL config (optional)
db.url=jdbc:postgresql://localhost:5432/lab10_testing
db.username=postgres
db.password=postgres
db.enabled=false
